apiVersion: v2
name: gowa
description: A Helm chart for Go WhatsApp Web Multidevice Admin API

type: application

# Chart version follows Semantic Versioning (https://semver.org/)
version: 7.10.3

# Application version being deployed
# NOTE: Uses '-' instead of '+' because Docker tags don't support '+'
appVersion: "v7.10.1-2"

# Chart metadata
home: https://github.com/chatwoot-br/go-whatsapp-web-multidevice
sources:
  - https://github.com/chatwoot-br/go-whatsapp-web-multidevice
maintainers:
  - name: chatwoot-br
    url: https://github.com/chatwoot-br
keywords:
  - whatsapp
  - api
  - messaging
  - multi-device
  - supervisord
  - admin
