apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gowa.fullname" . }}
  labels:
    {{- include "gowa.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_BASIC_AUTH: {{ .Values.auth.basicAuth | quote }}
  WHATSAPP_WEBHOOK: {{ .Values.webhook.urls | quote }}
  WHATSAPP_WEBHOOK_SECRET: {{ .Values.webhook.secret | quote }}
  DB_URI: {{ .Values.database.uri | quote }}
  DB_KEYS_URI: {{ .Values.database.keysUri | quote }}
  {{- if .Values.whatsapp.proxy.url }}
  WHATSAPP_PROXY_URL: {{ .Values.whatsapp.proxy.url | quote }}
  {{- end }}
