{{- if or .Values.admin.token .Values.admin.supervisor.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gowa.fullname" . }}-secret
  labels:
    {{- include "gowa.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.admin.token }}
  admin-token: {{ .Values.admin.token | b64enc }}
  {{- end }}
  {{- if .Values.admin.supervisor.password }}
  supervisor-username: {{ .Values.admin.supervisor.username | b64enc }}
  supervisor-password: {{ .Values.admin.supervisor.password | b64enc }}
  {{- end }}
{{- end }}
